spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 내가 가진 엔티티를 다 드랍시키고 create 시켜주는거래
      ddl-auto: create
  properties:
    hibernate:
      format_sql: true

  logging.level:
    org.hibernate.SQL: debug
    org.hiberanate.type: trace

